name: Build and upload to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  buildAndPushImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:  mvn clean install
        
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ github.run_number }}
  deploy:
    needs: buildAndPushImage
    runs-on: ubuntu-latest
    steps:
      - name: changing the deployment of git repo
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository_owner }}/spring-app-deploymentse-apps
            token: ${{ secrets.REPO_SECRET }} # `GH_PAT` is a secret that contains your PAT
            path: helm

      - name: Get repository path
        id: get-repo-path
        run: |
            echo "::set-output name=repo-path::${{ github.repository }}"

      - name: Update image version in helm-chart-repo/values.yaml
        run: |
          yq --inplace '.image.tag = "${{ github.run_number }}"' helm/deploy/values.yaml
      - name: Commit and push changes to Helm chart repository
        run: |
          cd helm/deploy
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add values.yaml
          git commit -m "Updated image version to ${{ github.run_number }}"
          git push https://github.com/${{ github.repository_owner }}/spring-app-deploymentse-apps.git main